import {
  css,
  html,
  js,
  react,
  ts,
  render,
  security,
  api,
  build,
  principles,
  architecture,
  infrastructure,
  network,
  browser,
  performance,
  deploy,
} from "../knowledge";

export const knowledgeContent = [
  { rowTitle: "HTML", content: html },
  { rowTitle: "CSS", content: css },
  { rowTitle: "JS", content: js },
  { rowTitle: "TS", content: ts },
  { rowTitle: "React", content: react },
  { rowTitle: "Рендеринг", content: render },
  { rowTitle: "Безопасность", content: security },
  { rowTitle: "API", content: api },
  { rowTitle: "Системы сборки", content: build },
  {
    rowTitle: "Принципы разработки программного обеспечения",
    content: principles,
  },
  { rowTitle: "Дизайн/архитектура приложений", content: architecture },
  { rowTitle: "Инфраструктура", content: infrastructure },
  { rowTitle: "Сеть", content: network },
  { rowTitle: "Браузер", content: browser },
  { rowTitle: "Frontend Performance", content: performance },
  { rowTitle: "Deploy/CI/CD", content: deploy },
];
